//True Conditions :
var car = 'Toyota';
console.log("Is car == 'Toyota'? I predict True.");
console.log(car == 'Toyota');
var mobile = 'Infinix';
console.log("Is mobile == 'Infinix'? I predict True.");
console.log(mobile == 'Infinix');
var motorcycle = 'Honda';
console.log("Is motorcycle == 'Honda'? I predict True.");
console.log(motorcycle == 'Honda');
var laptop = 'DELL';
console.log("Is laptop == 'DELL'? I predict True.");
console.log(laptop == 'DELL');
var favFood = 'Biryani';
console.log("Is favFood == 'Biryani'? I predict True.");
console.log(favFood == 'Biryani');
//False Conditions :
var fullName = 'Faiza Kherad';
console.log("Is fullName == 'Maryam'? I predict False.");
console.log(fullName == 'Maryam');
var country = 'Pakistan';
console.log("Is country == 'Afghanistan'? I predict False.");
console.log(country == 'Afghanistan');
var planet = 'Earth';
console.log("Is planet == 'Venus'? I predict False.");
console.log(planet == 'Venus');
var sports = 'olympic';
console.log("Is sports == 'cricket'? I predict False.");
console.log(sports == 'cricket');
var flowers = 'rose';
console.log("Is flowers  == 'jasmine'? I predict False.");
console.log(flowers == 'jasmine');
